# Generated by Django 5.2.4 on 2025-08-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhalt', models.TextField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
