# Generated by Django 5.2.4 on 2025-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nachricht',
            name='inhalt',
        ),
        migrations.AddField(
            model_name='nachricht',
            name='alter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nachricht',
            name='groesse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nachricht',
            name='name',
            field=models.CharField(default='Unbekannt', max_length=100),
            preserve_default=False,
        ),
    ]
