# Generated by Django 5.2.4 on 2025-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nachricht',
            name='alter',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='groesse',
        ),
        migrations.RemoveField(
            model_name='nachricht',
            name='name',
        ),
        migrations.AddField(
            model_name='nachricht',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
