# Generated by Django 5.2.4 on 2025-08-19 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_nachricht_alter_remove_nachricht_groesse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='anfangsdatum',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='enddatum',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
