# Generated by Django 5.2.4 on 2025-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_position_anfangsdatum_position_enddatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='enddatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
